writing_detector_data = {
    "ai_writing_indicators": {
        "filler_phrases": [
            "stands as",
            "serves as",
            "is a testament",
            "is a reminder",
            "vital role",
            "significant role",
            "crucial role",
            "pivotal role",
            "key role",
            "vital moment",
            "significant moment",
            "crucial moment",
            "pivotal moment",
            "key moment",
            "underscores its importance",
            "underscores its significance",
            "highlights its importance",
            "highlights its significance",
            "reflects broader",
            "symbolizing its ongoing",
            "symbolizing its enduring",
            "symbolizing its lasting",
            "contributing to the",
            "setting the stage for",
            "marking the",
            "shaping the",
            "represents a shift",
            "marks a shift",
            "key turning point",
            "evolving landscape",
            "focal point",
            "indelible mark",
            "deeply rooted",
            "plays a crucial role",
            "shaping the future",
            "driving force",
            "cornerstone",
            "quintessential",
            "paradigm shift",
            "transformative power",
            "catalyzes change",
            "orchestrates",
            "amplifies the narrative",
            "underscores the reality",
            "serves as a beacon",
            "epitomizes excellence",
        ],
        "credibility_markers": [
            "independent coverage",
            "local media outlets",
            "regional media outlets",
            "national media outlets",
            "music outlets",
            "business outlets",
            "tech outlets",
            "profiled in",
            "written by a leading expert",
            "active social media presence",
            "cited by industry leaders",
            "featured in publications",
            "recognized by experts",
            "mentioned in reports",
            "according to research",
            "according to studies",
            "verified by sources",
            "backed by data",
            "supported by evidence",
        ],
        "descriptive_overuse": [
            "highlighting",
            "underscoring",
            "emphasizing",
            "ensuring",
            "reflecting",
            "symbolizing",
            "contributing to",
            "cultivating",
            "fostering",
            "encompassing",
            "valuable insights",
            "align with",
            "resonate with",
            "the old guard",
            "boasts a",
            "vibrant",
            "rich",
            "profound",
            "enhancing",
            "showcasing",
            "exemplifies",
            "commitment to",
            "natural beauty",
            "nestled",
            "in the heart of",
            "groundbreaking",
            "renowned",
            "featuring",
            "diverse array",
            "myriad",
            "nuanced",
            "intricate web",
            "multifaceted",
            "sophisticated",
            "elegant solution",
            "robust framework",
            "holistic approach",
            "seamless integration",
            "synergistic",
            "unprecedented",
            "cutting-edge",
            "state-of-the-art",
            "innovative approach",
            "transformational",
            "revolutionary",
            "game-changing",
            "striking a balance",
            "delicate equilibrium",
            "intrinsic value",
            "heightened awareness",
            "bolster confidence",
            "streamlined process",
            "optimized performance",
        ],
        "attribution_patterns": [
            "Industry reports",
            "Observers have cited",
            "Experts argue",
            "Some critics argue",
            "several sources",
            "several publications",
            "such as",
            "for instance",
            "in particular",
            "notably",
            "specifically",
            "it is worth noting",
            "it should be noted",
            "furthermore",
            "moreover",
        ],
        "structural_patterns": [
            "Despite its",
            "faces several challenges",
            "Despite these challenges",
            "Challenges and Legacy",
            "Future Outlook",
            "Implications and Impact",
            "Looking Forward",
            "The Bigger Picture",
            "In Conclusion",
            "Key Takeaways",
            "The Way Forward",
            "Emerging Trends",
            "Potential Challenges",
            "Opportunities for Growth",
        ],
        "commonly_overused_words": [
            "Additionally",
            "align with",
            "boasts",
            "bolstered",
            "crucial",
            "delve",
            "emphasizing",
            "enduring",
            "enhance",
            "fostering",
            "garner",
            "highlight",
            "interplay",
            "intricate",
            "intricacies",
            "key",
            "landscape",
            "meticulous",
            "meticulously",
            "pivotal",
            "showcase",
            "tapestry",
            "testament",
            "underscore",
            "valuable",
            "vibrant",
            "compelling",
            "remarkable",
            "noteworthy",
            "significant",
            "substantial",
            "considerable",
            "extensive",
            "comprehensive",
            "thorough",
            "rigorous",
            "meticulous",
            "distinctive",
            "exceptional",
            "outstanding",
            "unprecedented",
            "distinctive approach",
            "thoughtful consideration",
            "strategic importance",
            "critical examination",
            "deeper understanding",
            "broader perspective",
            "nuanced view",
            "complex landscape",
        ],
        "common_constructions": [
            "serves as",
            "stands as",
            "marks",
            "represents",
            "boasts",
            "features",
            "offers",
        ],
    }
}

writing_styles = {
    "narrative_story": {
        "description": "Story-style narrative writing",
        "example": "A faint hum echoed through the empty hallway as Adrian stepped forward, his fingers brushing against the cold wall. The lights flickered—not randomly, but almost deliberately, as if reacting to his presence. He paused. There it was again. A whisper. Not from behind. Not ahead. But inside. 'Not everything lost is gone.' His breath hitched. He didn't remember this place, and yet… it felt like something here remembered him.",
    },
    "technical_beginner": {
        "description": "Technical explanation for beginners",
        "example": "APIs (Application Programming Interfaces) allow different software systems to communicate with each other. Think of an API as a waiter in a restaurant—it takes your request, delivers it to the kitchen, and brings back the response. For example, when you use a weather app, it doesn't generate weather data itself. Instead, it sends a request to a weather API, which returns the current temperature and forecast.",
    },
    "opinion_argumentative": {
        "description": "Opinion or argumentative writing",
        "example": "Remote work is often praised for increasing productivity, but that claim isn't universally true. While some individuals thrive in flexible environments, others struggle with distractions and lack of structure. Productivity, therefore, is less about location and more about discipline, environment design, and clarity of goals. Organizations that ignore this nuance risk overestimating the benefits of remote setups.",
    },
    "psychological_reflective": {
        "description": "Psychological or reflective writing",
        "example": "There's a peculiar comfort in distraction. It asks nothing from you—no effort, no vulnerability, no risk of failure. Scrolling endlessly feels easier than facing a blank page or an unsolved problem. But over time, this comfort becomes a quiet trap. The more you escape into distraction, the harder it becomes to return to focus. Not because you've lost the ability—but because you've trained your mind to avoid discomfort.",
    },
    "business_analytical": {
        "description": "Business or analytical writing",
        "example": "Startups often fail not because of poor technology, but due to a lack of market alignment. Building a technically sound product does not guarantee user adoption. Successful companies prioritize feedback loops early—testing assumptions, validating demand, and iterating quickly. In contrast, teams that overinvest in development before validation frequently waste both time and resources.",
    },
    "data_interpretation": {
        "description": "Data interpretation style",
        "example": "A recent survey showed that 68% of users abandon an application within the first week of installation. The primary reasons cited include poor user experience (45%), lack of perceived value (30%), and performance issues (25%). This suggests that initial onboarding and first impressions play a critical role in user retention. Improving these areas could significantly reduce early churn rates.",
    },
}
